CREATE TABLE groups (
    group_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    member_one INTEGER REFERENCES users(email) NOT NULL,
    member_two INTEGER REFERENCES users(email) NOT NULL,
    past_match_1 INTEGER,
    past_match_2 INTEGER,
    past_match_3 INTEGER,
    past_match_4 INTEGER,
    past_match_5 INTEGER,
    past_match_6 INTEGER,
    past_match_7 INTEGER,
    past_match_8 INTEGER,
    past_match_9 INTEGER,
    past_match_10 INTEGER
);