ALTER TABLE users DROP COLUMN IF EXISTS yum_1;

ALTER TABLE users DROP COLUMN IF EXISTS yum_2;

ALTER TABLE users DROP COLUMN IF EXISTS yum_3;

ALTER TABLE users DROP COLUMN IF EXISTS yum_4;

ALTER TABLE users DROP COLUMN IF EXISTS yum_5;

ALTER TABLE users DROP COLUMN IF EXISTS yum_6;

ALTER TABLE users DROP COLUMN IF EXISTS yum_7;

ALTER TABLE users DROP COLUMN IF EXISTS yum_8;

ALTER TABLE users DROP COLUMN IF EXISTS yum_9;

ALTER TABLE users DROP COLUMN IF EXISTS yum_10;

ALTER TABLE users DROP COLUMN IF EXISTS yum_11;

ALTER TABLE users DROP COLUMN IF EXISTS yum_12;

ALTER TABLE users DROP COLUMN IF EXISTS yum_13;

ALTER TABLE users DROP COLUMN IF EXISTS yum_14;

ALTER TABLE users DROP COLUMN IF EXISTS yum_15;

ALTER TABLE users DROP COLUMN IF EXISTS yum_16;

ALTER TABLE users DROP COLUMN IF EXISTS yum_17;

ALTER TABLE users DROP COLUMN IF EXISTS yum_18;

ALTER TABLE users DROP COLUMN IF EXISTS yum_19;

ALTER TABLE users DROP COLUMN IF EXISTS yum_20;

ALTER TABLE users DROP COLUMN IF EXISTS yum_21;

ALTER TABLE users DROP COLUMN IF EXISTS yum_22;

ALTER TABLE users DROP COLUMN IF EXISTS yum_23;

ALTER TABLE users DROP COLUMN IF EXISTS yum_24;

ALTER TABLE users DROP COLUMN IF EXISTS yum_25;

ALTER TABLE users DROP COLUMN IF EXISTS yum_26;

ALTER TABLE users DROP COLUMN IF EXISTS yum_27;

ALTER TABLE users DROP COLUMN IF EXISTS yum_28;

ALTER TABLE users DROP COLUMN IF EXISTS yum_29;

ALTER TABLE users DROP COLUMN IF EXISTS yum_30;

ALTER TABLE users DROP COLUMN IF EXISTS yum_31;

ALTER TABLE users DROP COLUMN IF EXISTS yum_32;

ALTER TABLE users DROP COLUMN IF EXISTS yum_33;

ALTER TABLE users DROP COLUMN IF EXISTS yum_34;

ALTER TABLE users DROP COLUMN IF EXISTS yum_35;

ALTER TABLE users DROP COLUMN IF EXISTS yum_36;

ALTER TABLE users DROP COLUMN IF EXISTS yum_37;

ALTER TABLE users DROP COLUMN IF EXISTS yum_38;

ALTER TABLE users DROP COLUMN IF EXISTS yum_39;

ALTER TABLE users DROP COLUMN IF EXISTS yum_40;

ALTER TABLE users DROP COLUMN IF EXISTS yum_41;

ALTER TABLE users DROP COLUMN IF EXISTS yum_42;

ALTER TABLE users DROP COLUMN IF EXISTS yum_43;

ALTER TABLE users DROP COLUMN IF EXISTS yum_44;

ALTER TABLE users DROP COLUMN IF EXISTS yum_45;

ALTER TABLE users DROP COLUMN IF EXISTS yum_46;

ALTER TABLE users DROP COLUMN IF EXISTS yum_47;

ALTER TABLE users DROP COLUMN IF EXISTS yum_48;

ALTER TABLE users DROP COLUMN IF EXISTS yum_49;

ALTER TABLE users DROP COLUMN IF EXISTS yum_50;